version: '3.0'
services:
  resource-server:
    image: openmhealth/shimmer-resource-server
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - mongo
    env_file:
      - ./shimmer-resource-server.env
    ports:
      - "8084:8083"

  mongo:
    image: mongo
    restart: always

  console:
    image: openmhealth/shimmer-console
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - resource-server

  mdata-db:
    image: postgres:latest
    restart: always
    expose:
      - 5432
    env_file:
      - ./omhserver/postgres.env

  mdata-app:
    build:
      context: ./omhserver
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8888:8080"
    env_file:
      - ./omhserver/omh-server.env
    depends_on:
      - mdata-db

  omh-on-fhir-client:
      build:
        #specifiy the project build context
        context: ./omhclient
        #specifiy the Dockerfile to use
        dockerfile: Dockerfile
      restart: always
      #bind host port 8989 to container port 8080
      ports:
         - "8989:8080"